using System.Numerics;
using DoubleSharp.MathPlus;
namespace Tests; 

[TestFixture]
public class SwizzleTests {
	[Test]
	public void Swizzle2x2() {
		var vec = new Vector2(6f, 7f);
		var vecd = new Vector2D(6, 7);
		Assert.Multiple(() => {
			Assert.That(vec.XX(), Is.EqualTo(new Vector2(6f, 6f)));
			Assert.That(vec.XY(), Is.EqualTo(new Vector2(6f, 7f)));
			Assert.That(vec.YX(), Is.EqualTo(new Vector2(7f, 6f)));
			Assert.That(vec.YY(), Is.EqualTo(new Vector2(7f, 7f)));
			Assert.That(vecd.XX(), Is.EqualTo(new Vector2D(6f, 6f)));
			Assert.That(vecd.XY(), Is.EqualTo(new Vector2D(6f, 7f)));
			Assert.That(vecd.YX(), Is.EqualTo(new Vector2D(7f, 6f)));
			Assert.That(vecd.YY(), Is.EqualTo(new Vector2D(7f, 7f)));
		});
	}

	[Test]
	public void Swizzle3x2() {
		var vec = new Vector3(6f, 7f, 8f);
		Assert.Multiple(() => {
			Assert.That(vec.XX(), Is.EqualTo(new Vector2(6f, 6f)));
			Assert.That(vec.XY(), Is.EqualTo(new Vector2(6f, 7f)));
			Assert.That(vec.XZ(), Is.EqualTo(new Vector2(6f, 8f)));
			Assert.That(vec.YX(), Is.EqualTo(new Vector2(7f, 6f)));
			Assert.That(vec.YY(), Is.EqualTo(new Vector2(7f, 7f)));
			Assert.That(vec.YZ(), Is.EqualTo(new Vector2(7f, 8f)));
			Assert.That(vec.ZX(), Is.EqualTo(new Vector2(8f, 6f)));
			Assert.That(vec.ZY(), Is.EqualTo(new Vector2(8f, 7f)));
			Assert.That(vec.ZZ(), Is.EqualTo(new Vector2(8f, 8f)));
		});
	}

	[Test]
	public void Swizzle4x2() {
		var vec = new Vector4(6f, 7f, 8f, 9f);
		Assert.Multiple(() => {
			Assert.That(vec.XX(), Is.EqualTo(new Vector2(6f, 6f)));
			Assert.That(vec.XY(), Is.EqualTo(new Vector2(6f, 7f)));
			Assert.That(vec.XZ(), Is.EqualTo(new Vector2(6f, 8f)));
			Assert.That(vec.XW(), Is.EqualTo(new Vector2(6f, 9f)));
			Assert.That(vec.YX(), Is.EqualTo(new Vector2(7f, 6f)));
			Assert.That(vec.YY(), Is.EqualTo(new Vector2(7f, 7f)));
			Assert.That(vec.YZ(), Is.EqualTo(new Vector2(7f, 8f)));
			Assert.That(vec.YW(), Is.EqualTo(new Vector2(7f, 9f)));
			Assert.That(vec.ZX(), Is.EqualTo(new Vector2(8f, 6f)));
			Assert.That(vec.ZY(), Is.EqualTo(new Vector2(8f, 7f)));
			Assert.That(vec.ZZ(), Is.EqualTo(new Vector2(8f, 8f)));
			Assert.That(vec.ZW(), Is.EqualTo(new Vector2(8f, 9f)));
			Assert.That(vec.WX(), Is.EqualTo(new Vector2(9f, 6f)));
			Assert.That(vec.WY(), Is.EqualTo(new Vector2(9f, 7f)));
			Assert.That(vec.WZ(), Is.EqualTo(new Vector2(9f, 8f)));
			Assert.That(vec.WW(), Is.EqualTo(new Vector2(9f, 9f)));
		});
	}

	[Test]
	public void Swizzle2x3() {
		var vec = new Vector2(6f, 7f);
		Assert.Multiple(() => {
			Assert.That(vec.XXX(), Is.EqualTo(new Vector3(6f, 6f, 6f)));
			Assert.That(vec.XXY(), Is.EqualTo(new Vector3(6f, 6f, 7f)));
			Assert.That(vec.XYX(), Is.EqualTo(new Vector3(6f, 7f, 6f)));
			Assert.That(vec.XYY(), Is.EqualTo(new Vector3(6f, 7f, 7f)));
			Assert.That(vec.YXX(), Is.EqualTo(new Vector3(7f, 6f, 6f)));
			Assert.That(vec.YXY(), Is.EqualTo(new Vector3(7f, 6f, 7f)));
			Assert.That(vec.YYX(), Is.EqualTo(new Vector3(7f, 7f, 6f)));
			Assert.That(vec.YYY(), Is.EqualTo(new Vector3(7f, 7f, 7f)));
		});
	}

	[Test]
	public void Swizzle3x3() {
		var vec = new Vector3(6f, 7f, 8f);
		Assert.Multiple(() => {
			Assert.That(vec.XXX(), Is.EqualTo(new Vector3(6f, 6f, 6f)));
			Assert.That(vec.XXY(), Is.EqualTo(new Vector3(6f, 6f, 7f)));
			Assert.That(vec.XXZ(), Is.EqualTo(new Vector3(6f, 6f, 8f)));
			Assert.That(vec.XYX(), Is.EqualTo(new Vector3(6f, 7f, 6f)));
			Assert.That(vec.XYY(), Is.EqualTo(new Vector3(6f, 7f, 7f)));
			Assert.That(vec.XYZ(), Is.EqualTo(new Vector3(6f, 7f, 8f)));
			Assert.That(vec.XZX(), Is.EqualTo(new Vector3(6f, 8f, 6f)));
			Assert.That(vec.XZY(), Is.EqualTo(new Vector3(6f, 8f, 7f)));
			Assert.That(vec.XZZ(), Is.EqualTo(new Vector3(6f, 8f, 8f)));
			Assert.That(vec.YXX(), Is.EqualTo(new Vector3(7f, 6f, 6f)));
			Assert.That(vec.YXY(), Is.EqualTo(new Vector3(7f, 6f, 7f)));
			Assert.That(vec.YXZ(), Is.EqualTo(new Vector3(7f, 6f, 8f)));
			Assert.That(vec.YYX(), Is.EqualTo(new Vector3(7f, 7f, 6f)));
			Assert.That(vec.YYY(), Is.EqualTo(new Vector3(7f, 7f, 7f)));
			Assert.That(vec.YYZ(), Is.EqualTo(new Vector3(7f, 7f, 8f)));
			Assert.That(vec.YZX(), Is.EqualTo(new Vector3(7f, 8f, 6f)));
			Assert.That(vec.YZY(), Is.EqualTo(new Vector3(7f, 8f, 7f)));
			Assert.That(vec.YZZ(), Is.EqualTo(new Vector3(7f, 8f, 8f)));
			Assert.That(vec.ZXX(), Is.EqualTo(new Vector3(8f, 6f, 6f)));
			Assert.That(vec.ZXY(), Is.EqualTo(new Vector3(8f, 6f, 7f)));
			Assert.That(vec.ZXZ(), Is.EqualTo(new Vector3(8f, 6f, 8f)));
			Assert.That(vec.ZYX(), Is.EqualTo(new Vector3(8f, 7f, 6f)));
			Assert.That(vec.ZYY(), Is.EqualTo(new Vector3(8f, 7f, 7f)));
			Assert.That(vec.ZYZ(), Is.EqualTo(new Vector3(8f, 7f, 8f)));
			Assert.That(vec.ZZX(), Is.EqualTo(new Vector3(8f, 8f, 6f)));
			Assert.That(vec.ZZY(), Is.EqualTo(new Vector3(8f, 8f, 7f)));
			Assert.That(vec.ZZZ(), Is.EqualTo(new Vector3(8f, 8f, 8f)));
		});
	}

	[Test]
	public void Swizzle4x3() {
		var vec = new Vector4(6f, 7f, 8f, 9f);
		Assert.Multiple(() => {
			Assert.That(vec.XXX(), Is.EqualTo(new Vector3(6f, 6f, 6f)));
			Assert.That(vec.XXY(), Is.EqualTo(new Vector3(6f, 6f, 7f)));
			Assert.That(vec.XXZ(), Is.EqualTo(new Vector3(6f, 6f, 8f)));
			Assert.That(vec.XXW(), Is.EqualTo(new Vector3(6f, 6f, 9f)));
			Assert.That(vec.XYX(), Is.EqualTo(new Vector3(6f, 7f, 6f)));
			Assert.That(vec.XYY(), Is.EqualTo(new Vector3(6f, 7f, 7f)));
			Assert.That(vec.XYZ(), Is.EqualTo(new Vector3(6f, 7f, 8f)));
			Assert.That(vec.XYW(), Is.EqualTo(new Vector3(6f, 7f, 9f)));
			Assert.That(vec.XZX(), Is.EqualTo(new Vector3(6f, 8f, 6f)));
			Assert.That(vec.XZY(), Is.EqualTo(new Vector3(6f, 8f, 7f)));
			Assert.That(vec.XZZ(), Is.EqualTo(new Vector3(6f, 8f, 8f)));
			Assert.That(vec.XZW(), Is.EqualTo(new Vector3(6f, 8f, 9f)));
			Assert.That(vec.XWX(), Is.EqualTo(new Vector3(6f, 9f, 6f)));
			Assert.That(vec.XWY(), Is.EqualTo(new Vector3(6f, 9f, 7f)));
			Assert.That(vec.XWZ(), Is.EqualTo(new Vector3(6f, 9f, 8f)));
			Assert.That(vec.XWW(), Is.EqualTo(new Vector3(6f, 9f, 9f)));
			Assert.That(vec.YXX(), Is.EqualTo(new Vector3(7f, 6f, 6f)));
			Assert.That(vec.YXY(), Is.EqualTo(new Vector3(7f, 6f, 7f)));
			Assert.That(vec.YXZ(), Is.EqualTo(new Vector3(7f, 6f, 8f)));
			Assert.That(vec.YXW(), Is.EqualTo(new Vector3(7f, 6f, 9f)));
			Assert.That(vec.YYX(), Is.EqualTo(new Vector3(7f, 7f, 6f)));
			Assert.That(vec.YYY(), Is.EqualTo(new Vector3(7f, 7f, 7f)));
			Assert.That(vec.YYZ(), Is.EqualTo(new Vector3(7f, 7f, 8f)));
			Assert.That(vec.YYW(), Is.EqualTo(new Vector3(7f, 7f, 9f)));
			Assert.That(vec.YZX(), Is.EqualTo(new Vector3(7f, 8f, 6f)));
			Assert.That(vec.YZY(), Is.EqualTo(new Vector3(7f, 8f, 7f)));
			Assert.That(vec.YZZ(), Is.EqualTo(new Vector3(7f, 8f, 8f)));
			Assert.That(vec.YZW(), Is.EqualTo(new Vector3(7f, 8f, 9f)));
			Assert.That(vec.YWX(), Is.EqualTo(new Vector3(7f, 9f, 6f)));
			Assert.That(vec.YWY(), Is.EqualTo(new Vector3(7f, 9f, 7f)));
			Assert.That(vec.YWZ(), Is.EqualTo(new Vector3(7f, 9f, 8f)));
			Assert.That(vec.YWW(), Is.EqualTo(new Vector3(7f, 9f, 9f)));
			Assert.That(vec.ZXX(), Is.EqualTo(new Vector3(8f, 6f, 6f)));
			Assert.That(vec.ZXY(), Is.EqualTo(new Vector3(8f, 6f, 7f)));
			Assert.That(vec.ZXZ(), Is.EqualTo(new Vector3(8f, 6f, 8f)));
			Assert.That(vec.ZXW(), Is.EqualTo(new Vector3(8f, 6f, 9f)));
			Assert.That(vec.ZYX(), Is.EqualTo(new Vector3(8f, 7f, 6f)));
			Assert.That(vec.ZYY(), Is.EqualTo(new Vector3(8f, 7f, 7f)));
			Assert.That(vec.ZYZ(), Is.EqualTo(new Vector3(8f, 7f, 8f)));
			Assert.That(vec.ZYW(), Is.EqualTo(new Vector3(8f, 7f, 9f)));
			Assert.That(vec.ZZX(), Is.EqualTo(new Vector3(8f, 8f, 6f)));
			Assert.That(vec.ZZY(), Is.EqualTo(new Vector3(8f, 8f, 7f)));
			Assert.That(vec.ZZZ(), Is.EqualTo(new Vector3(8f, 8f, 8f)));
			Assert.That(vec.ZZW(), Is.EqualTo(new Vector3(8f, 8f, 9f)));
			Assert.That(vec.ZWX(), Is.EqualTo(new Vector3(8f, 9f, 6f)));
			Assert.That(vec.ZWY(), Is.EqualTo(new Vector3(8f, 9f, 7f)));
			Assert.That(vec.ZWZ(), Is.EqualTo(new Vector3(8f, 9f, 8f)));
			Assert.That(vec.ZWW(), Is.EqualTo(new Vector3(8f, 9f, 9f)));
			Assert.That(vec.WXX(), Is.EqualTo(new Vector3(9f, 6f, 6f)));
			Assert.That(vec.WXY(), Is.EqualTo(new Vector3(9f, 6f, 7f)));
			Assert.That(vec.WXZ(), Is.EqualTo(new Vector3(9f, 6f, 8f)));
			Assert.That(vec.WXW(), Is.EqualTo(new Vector3(9f, 6f, 9f)));
			Assert.That(vec.WYX(), Is.EqualTo(new Vector3(9f, 7f, 6f)));
			Assert.That(vec.WYY(), Is.EqualTo(new Vector3(9f, 7f, 7f)));
			Assert.That(vec.WYZ(), Is.EqualTo(new Vector3(9f, 7f, 8f)));
			Assert.That(vec.WYW(), Is.EqualTo(new Vector3(9f, 7f, 9f)));
			Assert.That(vec.WZX(), Is.EqualTo(new Vector3(9f, 8f, 6f)));
			Assert.That(vec.WZY(), Is.EqualTo(new Vector3(9f, 8f, 7f)));
			Assert.That(vec.WZZ(), Is.EqualTo(new Vector3(9f, 8f, 8f)));
			Assert.That(vec.WZW(), Is.EqualTo(new Vector3(9f, 8f, 9f)));
			Assert.That(vec.WWX(), Is.EqualTo(new Vector3(9f, 9f, 6f)));
			Assert.That(vec.WWY(), Is.EqualTo(new Vector3(9f, 9f, 7f)));
			Assert.That(vec.WWZ(), Is.EqualTo(new Vector3(9f, 9f, 8f)));
			Assert.That(vec.WWW(), Is.EqualTo(new Vector3(9f, 9f, 9f)));
		});
	}

	[Test]
	public void Swizzle2x4() {
		var vec = new Vector2(6f, 7f);
		Assert.Multiple(() => {
			Assert.That(vec.XXXX(), Is.EqualTo(new Vector4(6f, 6f, 6f, 6f)));
			Assert.That(vec.XXXY(), Is.EqualTo(new Vector4(6f, 6f, 6f, 7f)));
			Assert.That(vec.XXYX(), Is.EqualTo(new Vector4(6f, 6f, 7f, 6f)));
			Assert.That(vec.XXYY(), Is.EqualTo(new Vector4(6f, 6f, 7f, 7f)));
			Assert.That(vec.XYXX(), Is.EqualTo(new Vector4(6f, 7f, 6f, 6f)));
			Assert.That(vec.XYXY(), Is.EqualTo(new Vector4(6f, 7f, 6f, 7f)));
			Assert.That(vec.XYYX(), Is.EqualTo(new Vector4(6f, 7f, 7f, 6f)));
			Assert.That(vec.XYYY(), Is.EqualTo(new Vector4(6f, 7f, 7f, 7f)));
			Assert.That(vec.YXXX(), Is.EqualTo(new Vector4(7f, 6f, 6f, 6f)));
			Assert.That(vec.YXXY(), Is.EqualTo(new Vector4(7f, 6f, 6f, 7f)));
			Assert.That(vec.YXYX(), Is.EqualTo(new Vector4(7f, 6f, 7f, 6f)));
			Assert.That(vec.YXYY(), Is.EqualTo(new Vector4(7f, 6f, 7f, 7f)));
			Assert.That(vec.YYXX(), Is.EqualTo(new Vector4(7f, 7f, 6f, 6f)));
			Assert.That(vec.YYXY(), Is.EqualTo(new Vector4(7f, 7f, 6f, 7f)));
			Assert.That(vec.YYYX(), Is.EqualTo(new Vector4(7f, 7f, 7f, 6f)));
			Assert.That(vec.YYYY(), Is.EqualTo(new Vector4(7f, 7f, 7f, 7f)));
		});
	}

	[Test]
	public void Swizzle3x4() {
		var vec = new Vector3(6f, 7f, 8f);
		Assert.Multiple(() => {
			Assert.That(vec.XXXX(), Is.EqualTo(new Vector4(6f, 6f, 6f, 6f)));
			Assert.That(vec.XXXY(), Is.EqualTo(new Vector4(6f, 6f, 6f, 7f)));
			Assert.That(vec.XXXZ(), Is.EqualTo(new Vector4(6f, 6f, 6f, 8f)));
			Assert.That(vec.XXYX(), Is.EqualTo(new Vector4(6f, 6f, 7f, 6f)));
			Assert.That(vec.XXYY(), Is.EqualTo(new Vector4(6f, 6f, 7f, 7f)));
			Assert.That(vec.XXYZ(), Is.EqualTo(new Vector4(6f, 6f, 7f, 8f)));
			Assert.That(vec.XXZX(), Is.EqualTo(new Vector4(6f, 6f, 8f, 6f)));
			Assert.That(vec.XXZY(), Is.EqualTo(new Vector4(6f, 6f, 8f, 7f)));
			Assert.That(vec.XXZZ(), Is.EqualTo(new Vector4(6f, 6f, 8f, 8f)));
			Assert.That(vec.XYXX(), Is.EqualTo(new Vector4(6f, 7f, 6f, 6f)));
			Assert.That(vec.XYXY(), Is.EqualTo(new Vector4(6f, 7f, 6f, 7f)));
			Assert.That(vec.XYXZ(), Is.EqualTo(new Vector4(6f, 7f, 6f, 8f)));
			Assert.That(vec.XYYX(), Is.EqualTo(new Vector4(6f, 7f, 7f, 6f)));
			Assert.That(vec.XYYY(), Is.EqualTo(new Vector4(6f, 7f, 7f, 7f)));
			Assert.That(vec.XYYZ(), Is.EqualTo(new Vector4(6f, 7f, 7f, 8f)));
			Assert.That(vec.XYZX(), Is.EqualTo(new Vector4(6f, 7f, 8f, 6f)));
			Assert.That(vec.XYZY(), Is.EqualTo(new Vector4(6f, 7f, 8f, 7f)));
			Assert.That(vec.XYZZ(), Is.EqualTo(new Vector4(6f, 7f, 8f, 8f)));
			Assert.That(vec.XZXX(), Is.EqualTo(new Vector4(6f, 8f, 6f, 6f)));
			Assert.That(vec.XZXY(), Is.EqualTo(new Vector4(6f, 8f, 6f, 7f)));
			Assert.That(vec.XZXZ(), Is.EqualTo(new Vector4(6f, 8f, 6f, 8f)));
			Assert.That(vec.XZYX(), Is.EqualTo(new Vector4(6f, 8f, 7f, 6f)));
			Assert.That(vec.XZYY(), Is.EqualTo(new Vector4(6f, 8f, 7f, 7f)));
			Assert.That(vec.XZYZ(), Is.EqualTo(new Vector4(6f, 8f, 7f, 8f)));
			Assert.That(vec.XZZX(), Is.EqualTo(new Vector4(6f, 8f, 8f, 6f)));
			Assert.That(vec.XZZY(), Is.EqualTo(new Vector4(6f, 8f, 8f, 7f)));
			Assert.That(vec.XZZZ(), Is.EqualTo(new Vector4(6f, 8f, 8f, 8f)));
			Assert.That(vec.YXXX(), Is.EqualTo(new Vector4(7f, 6f, 6f, 6f)));
			Assert.That(vec.YXXY(), Is.EqualTo(new Vector4(7f, 6f, 6f, 7f)));
			Assert.That(vec.YXXZ(), Is.EqualTo(new Vector4(7f, 6f, 6f, 8f)));
			Assert.That(vec.YXYX(), Is.EqualTo(new Vector4(7f, 6f, 7f, 6f)));
			Assert.That(vec.YXYY(), Is.EqualTo(new Vector4(7f, 6f, 7f, 7f)));
			Assert.That(vec.YXYZ(), Is.EqualTo(new Vector4(7f, 6f, 7f, 8f)));
			Assert.That(vec.YXZX(), Is.EqualTo(new Vector4(7f, 6f, 8f, 6f)));
			Assert.That(vec.YXZY(), Is.EqualTo(new Vector4(7f, 6f, 8f, 7f)));
			Assert.That(vec.YXZZ(), Is.EqualTo(new Vector4(7f, 6f, 8f, 8f)));
			Assert.That(vec.YYXX(), Is.EqualTo(new Vector4(7f, 7f, 6f, 6f)));
			Assert.That(vec.YYXY(), Is.EqualTo(new Vector4(7f, 7f, 6f, 7f)));
			Assert.That(vec.YYXZ(), Is.EqualTo(new Vector4(7f, 7f, 6f, 8f)));
			Assert.That(vec.YYYX(), Is.EqualTo(new Vector4(7f, 7f, 7f, 6f)));
			Assert.That(vec.YYYY(), Is.EqualTo(new Vector4(7f, 7f, 7f, 7f)));
			Assert.That(vec.YYYZ(), Is.EqualTo(new Vector4(7f, 7f, 7f, 8f)));
			Assert.That(vec.YYZX(), Is.EqualTo(new Vector4(7f, 7f, 8f, 6f)));
			Assert.That(vec.YYZY(), Is.EqualTo(new Vector4(7f, 7f, 8f, 7f)));
			Assert.That(vec.YYZZ(), Is.EqualTo(new Vector4(7f, 7f, 8f, 8f)));
			Assert.That(vec.YZXX(), Is.EqualTo(new Vector4(7f, 8f, 6f, 6f)));
			Assert.That(vec.YZXY(), Is.EqualTo(new Vector4(7f, 8f, 6f, 7f)));
			Assert.That(vec.YZXZ(), Is.EqualTo(new Vector4(7f, 8f, 6f, 8f)));
			Assert.That(vec.YZYX(), Is.EqualTo(new Vector4(7f, 8f, 7f, 6f)));
			Assert.That(vec.YZYY(), Is.EqualTo(new Vector4(7f, 8f, 7f, 7f)));
			Assert.That(vec.YZYZ(), Is.EqualTo(new Vector4(7f, 8f, 7f, 8f)));
			Assert.That(vec.YZZX(), Is.EqualTo(new Vector4(7f, 8f, 8f, 6f)));
			Assert.That(vec.YZZY(), Is.EqualTo(new Vector4(7f, 8f, 8f, 7f)));
			Assert.That(vec.YZZZ(), Is.EqualTo(new Vector4(7f, 8f, 8f, 8f)));
			Assert.That(vec.ZXXX(), Is.EqualTo(new Vector4(8f, 6f, 6f, 6f)));
			Assert.That(vec.ZXXY(), Is.EqualTo(new Vector4(8f, 6f, 6f, 7f)));
			Assert.That(vec.ZXXZ(), Is.EqualTo(new Vector4(8f, 6f, 6f, 8f)));
			Assert.That(vec.ZXYX(), Is.EqualTo(new Vector4(8f, 6f, 7f, 6f)));
			Assert.That(vec.ZXYY(), Is.EqualTo(new Vector4(8f, 6f, 7f, 7f)));
			Assert.That(vec.ZXYZ(), Is.EqualTo(new Vector4(8f, 6f, 7f, 8f)));
			Assert.That(vec.ZXZX(), Is.EqualTo(new Vector4(8f, 6f, 8f, 6f)));
			Assert.That(vec.ZXZY(), Is.EqualTo(new Vector4(8f, 6f, 8f, 7f)));
			Assert.That(vec.ZXZZ(), Is.EqualTo(new Vector4(8f, 6f, 8f, 8f)));
			Assert.That(vec.ZYXX(), Is.EqualTo(new Vector4(8f, 7f, 6f, 6f)));
			Assert.That(vec.ZYXY(), Is.EqualTo(new Vector4(8f, 7f, 6f, 7f)));
			Assert.That(vec.ZYXZ(), Is.EqualTo(new Vector4(8f, 7f, 6f, 8f)));
			Assert.That(vec.ZYYX(), Is.EqualTo(new Vector4(8f, 7f, 7f, 6f)));
			Assert.That(vec.ZYYY(), Is.EqualTo(new Vector4(8f, 7f, 7f, 7f)));
			Assert.That(vec.ZYYZ(), Is.EqualTo(new Vector4(8f, 7f, 7f, 8f)));
			Assert.That(vec.ZYZX(), Is.EqualTo(new Vector4(8f, 7f, 8f, 6f)));
			Assert.That(vec.ZYZY(), Is.EqualTo(new Vector4(8f, 7f, 8f, 7f)));
			Assert.That(vec.ZYZZ(), Is.EqualTo(new Vector4(8f, 7f, 8f, 8f)));
			Assert.That(vec.ZZXX(), Is.EqualTo(new Vector4(8f, 8f, 6f, 6f)));
			Assert.That(vec.ZZXY(), Is.EqualTo(new Vector4(8f, 8f, 6f, 7f)));
			Assert.That(vec.ZZXZ(), Is.EqualTo(new Vector4(8f, 8f, 6f, 8f)));
			Assert.That(vec.ZZYX(), Is.EqualTo(new Vector4(8f, 8f, 7f, 6f)));
			Assert.That(vec.ZZYY(), Is.EqualTo(new Vector4(8f, 8f, 7f, 7f)));
			Assert.That(vec.ZZYZ(), Is.EqualTo(new Vector4(8f, 8f, 7f, 8f)));
			Assert.That(vec.ZZZX(), Is.EqualTo(new Vector4(8f, 8f, 8f, 6f)));
			Assert.That(vec.ZZZY(), Is.EqualTo(new Vector4(8f, 8f, 8f, 7f)));
			Assert.That(vec.ZZZZ(), Is.EqualTo(new Vector4(8f, 8f, 8f, 8f)));
		});
	}

	[Test]
	public void Swizzle4x4() {
		var vec = new Vector4(6f, 7f, 8f, 9f);
		Assert.Multiple(() => {
			Assert.That(vec.XXXX(), Is.EqualTo(new Vector4(6f, 6f, 6f, 6f)));
			Assert.That(vec.XXXY(), Is.EqualTo(new Vector4(6f, 6f, 6f, 7f)));
			Assert.That(vec.XXXZ(), Is.EqualTo(new Vector4(6f, 6f, 6f, 8f)));
			Assert.That(vec.XXXW(), Is.EqualTo(new Vector4(6f, 6f, 6f, 9f)));
			Assert.That(vec.XXYX(), Is.EqualTo(new Vector4(6f, 6f, 7f, 6f)));
			Assert.That(vec.XXYY(), Is.EqualTo(new Vector4(6f, 6f, 7f, 7f)));
			Assert.That(vec.XXYZ(), Is.EqualTo(new Vector4(6f, 6f, 7f, 8f)));
			Assert.That(vec.XXYW(), Is.EqualTo(new Vector4(6f, 6f, 7f, 9f)));
			Assert.That(vec.XXZX(), Is.EqualTo(new Vector4(6f, 6f, 8f, 6f)));
			Assert.That(vec.XXZY(), Is.EqualTo(new Vector4(6f, 6f, 8f, 7f)));
			Assert.That(vec.XXZZ(), Is.EqualTo(new Vector4(6f, 6f, 8f, 8f)));
			Assert.That(vec.XXZW(), Is.EqualTo(new Vector4(6f, 6f, 8f, 9f)));
			Assert.That(vec.XXWX(), Is.EqualTo(new Vector4(6f, 6f, 9f, 6f)));
			Assert.That(vec.XXWY(), Is.EqualTo(new Vector4(6f, 6f, 9f, 7f)));
			Assert.That(vec.XXWZ(), Is.EqualTo(new Vector4(6f, 6f, 9f, 8f)));
			Assert.That(vec.XXWW(), Is.EqualTo(new Vector4(6f, 6f, 9f, 9f)));
			Assert.That(vec.XYXX(), Is.EqualTo(new Vector4(6f, 7f, 6f, 6f)));
			Assert.That(vec.XYXY(), Is.EqualTo(new Vector4(6f, 7f, 6f, 7f)));
			Assert.That(vec.XYXZ(), Is.EqualTo(new Vector4(6f, 7f, 6f, 8f)));
			Assert.That(vec.XYXW(), Is.EqualTo(new Vector4(6f, 7f, 6f, 9f)));
			Assert.That(vec.XYYX(), Is.EqualTo(new Vector4(6f, 7f, 7f, 6f)));
			Assert.That(vec.XYYY(), Is.EqualTo(new Vector4(6f, 7f, 7f, 7f)));
			Assert.That(vec.XYYZ(), Is.EqualTo(new Vector4(6f, 7f, 7f, 8f)));
			Assert.That(vec.XYYW(), Is.EqualTo(new Vector4(6f, 7f, 7f, 9f)));
			Assert.That(vec.XYZX(), Is.EqualTo(new Vector4(6f, 7f, 8f, 6f)));
			Assert.That(vec.XYZY(), Is.EqualTo(new Vector4(6f, 7f, 8f, 7f)));
			Assert.That(vec.XYZZ(), Is.EqualTo(new Vector4(6f, 7f, 8f, 8f)));
			Assert.That(vec.XYZW(), Is.EqualTo(new Vector4(6f, 7f, 8f, 9f)));
			Assert.That(vec.XYWX(), Is.EqualTo(new Vector4(6f, 7f, 9f, 6f)));
			Assert.That(vec.XYWY(), Is.EqualTo(new Vector4(6f, 7f, 9f, 7f)));
			Assert.That(vec.XYWZ(), Is.EqualTo(new Vector4(6f, 7f, 9f, 8f)));
			Assert.That(vec.XYWW(), Is.EqualTo(new Vector4(6f, 7f, 9f, 9f)));
			Assert.That(vec.XZXX(), Is.EqualTo(new Vector4(6f, 8f, 6f, 6f)));
			Assert.That(vec.XZXY(), Is.EqualTo(new Vector4(6f, 8f, 6f, 7f)));
			Assert.That(vec.XZXZ(), Is.EqualTo(new Vector4(6f, 8f, 6f, 8f)));
			Assert.That(vec.XZXW(), Is.EqualTo(new Vector4(6f, 8f, 6f, 9f)));
			Assert.That(vec.XZYX(), Is.EqualTo(new Vector4(6f, 8f, 7f, 6f)));
			Assert.That(vec.XZYY(), Is.EqualTo(new Vector4(6f, 8f, 7f, 7f)));
			Assert.That(vec.XZYZ(), Is.EqualTo(new Vector4(6f, 8f, 7f, 8f)));
			Assert.That(vec.XZYW(), Is.EqualTo(new Vector4(6f, 8f, 7f, 9f)));
			Assert.That(vec.XZZX(), Is.EqualTo(new Vector4(6f, 8f, 8f, 6f)));
			Assert.That(vec.XZZY(), Is.EqualTo(new Vector4(6f, 8f, 8f, 7f)));
			Assert.That(vec.XZZZ(), Is.EqualTo(new Vector4(6f, 8f, 8f, 8f)));
			Assert.That(vec.XZZW(), Is.EqualTo(new Vector4(6f, 8f, 8f, 9f)));
			Assert.That(vec.XZWX(), Is.EqualTo(new Vector4(6f, 8f, 9f, 6f)));
			Assert.That(vec.XZWY(), Is.EqualTo(new Vector4(6f, 8f, 9f, 7f)));
			Assert.That(vec.XZWZ(), Is.EqualTo(new Vector4(6f, 8f, 9f, 8f)));
			Assert.That(vec.XZWW(), Is.EqualTo(new Vector4(6f, 8f, 9f, 9f)));
			Assert.That(vec.XWXX(), Is.EqualTo(new Vector4(6f, 9f, 6f, 6f)));
			Assert.That(vec.XWXY(), Is.EqualTo(new Vector4(6f, 9f, 6f, 7f)));
			Assert.That(vec.XWXZ(), Is.EqualTo(new Vector4(6f, 9f, 6f, 8f)));
			Assert.That(vec.XWXW(), Is.EqualTo(new Vector4(6f, 9f, 6f, 9f)));
			Assert.That(vec.XWYX(), Is.EqualTo(new Vector4(6f, 9f, 7f, 6f)));
			Assert.That(vec.XWYY(), Is.EqualTo(new Vector4(6f, 9f, 7f, 7f)));
			Assert.That(vec.XWYZ(), Is.EqualTo(new Vector4(6f, 9f, 7f, 8f)));
			Assert.That(vec.XWYW(), Is.EqualTo(new Vector4(6f, 9f, 7f, 9f)));
			Assert.That(vec.XWZX(), Is.EqualTo(new Vector4(6f, 9f, 8f, 6f)));
			Assert.That(vec.XWZY(), Is.EqualTo(new Vector4(6f, 9f, 8f, 7f)));
			Assert.That(vec.XWZZ(), Is.EqualTo(new Vector4(6f, 9f, 8f, 8f)));
			Assert.That(vec.XWZW(), Is.EqualTo(new Vector4(6f, 9f, 8f, 9f)));
			Assert.That(vec.XWWX(), Is.EqualTo(new Vector4(6f, 9f, 9f, 6f)));
			Assert.That(vec.XWWY(), Is.EqualTo(new Vector4(6f, 9f, 9f, 7f)));
			Assert.That(vec.XWWZ(), Is.EqualTo(new Vector4(6f, 9f, 9f, 8f)));
			Assert.That(vec.XWWW(), Is.EqualTo(new Vector4(6f, 9f, 9f, 9f)));
			Assert.That(vec.YXXX(), Is.EqualTo(new Vector4(7f, 6f, 6f, 6f)));
			Assert.That(vec.YXXY(), Is.EqualTo(new Vector4(7f, 6f, 6f, 7f)));
			Assert.That(vec.YXXZ(), Is.EqualTo(new Vector4(7f, 6f, 6f, 8f)));
			Assert.That(vec.YXXW(), Is.EqualTo(new Vector4(7f, 6f, 6f, 9f)));
			Assert.That(vec.YXYX(), Is.EqualTo(new Vector4(7f, 6f, 7f, 6f)));
			Assert.That(vec.YXYY(), Is.EqualTo(new Vector4(7f, 6f, 7f, 7f)));
			Assert.That(vec.YXYZ(), Is.EqualTo(new Vector4(7f, 6f, 7f, 8f)));
			Assert.That(vec.YXYW(), Is.EqualTo(new Vector4(7f, 6f, 7f, 9f)));
			Assert.That(vec.YXZX(), Is.EqualTo(new Vector4(7f, 6f, 8f, 6f)));
			Assert.That(vec.YXZY(), Is.EqualTo(new Vector4(7f, 6f, 8f, 7f)));
			Assert.That(vec.YXZZ(), Is.EqualTo(new Vector4(7f, 6f, 8f, 8f)));
			Assert.That(vec.YXZW(), Is.EqualTo(new Vector4(7f, 6f, 8f, 9f)));
			Assert.That(vec.YXWX(), Is.EqualTo(new Vector4(7f, 6f, 9f, 6f)));
			Assert.That(vec.YXWY(), Is.EqualTo(new Vector4(7f, 6f, 9f, 7f)));
			Assert.That(vec.YXWZ(), Is.EqualTo(new Vector4(7f, 6f, 9f, 8f)));
			Assert.That(vec.YXWW(), Is.EqualTo(new Vector4(7f, 6f, 9f, 9f)));
			Assert.That(vec.YYXX(), Is.EqualTo(new Vector4(7f, 7f, 6f, 6f)));
			Assert.That(vec.YYXY(), Is.EqualTo(new Vector4(7f, 7f, 6f, 7f)));
			Assert.That(vec.YYXZ(), Is.EqualTo(new Vector4(7f, 7f, 6f, 8f)));
			Assert.That(vec.YYXW(), Is.EqualTo(new Vector4(7f, 7f, 6f, 9f)));
			Assert.That(vec.YYYX(), Is.EqualTo(new Vector4(7f, 7f, 7f, 6f)));
			Assert.That(vec.YYYY(), Is.EqualTo(new Vector4(7f, 7f, 7f, 7f)));
			Assert.That(vec.YYYZ(), Is.EqualTo(new Vector4(7f, 7f, 7f, 8f)));
			Assert.That(vec.YYYW(), Is.EqualTo(new Vector4(7f, 7f, 7f, 9f)));
			Assert.That(vec.YYZX(), Is.EqualTo(new Vector4(7f, 7f, 8f, 6f)));
			Assert.That(vec.YYZY(), Is.EqualTo(new Vector4(7f, 7f, 8f, 7f)));
			Assert.That(vec.YYZZ(), Is.EqualTo(new Vector4(7f, 7f, 8f, 8f)));
			Assert.That(vec.YYZW(), Is.EqualTo(new Vector4(7f, 7f, 8f, 9f)));
			Assert.That(vec.YYWX(), Is.EqualTo(new Vector4(7f, 7f, 9f, 6f)));
			Assert.That(vec.YYWY(), Is.EqualTo(new Vector4(7f, 7f, 9f, 7f)));
			Assert.That(vec.YYWZ(), Is.EqualTo(new Vector4(7f, 7f, 9f, 8f)));
			Assert.That(vec.YYWW(), Is.EqualTo(new Vector4(7f, 7f, 9f, 9f)));
			Assert.That(vec.YZXX(), Is.EqualTo(new Vector4(7f, 8f, 6f, 6f)));
			Assert.That(vec.YZXY(), Is.EqualTo(new Vector4(7f, 8f, 6f, 7f)));
			Assert.That(vec.YZXZ(), Is.EqualTo(new Vector4(7f, 8f, 6f, 8f)));
			Assert.That(vec.YZXW(), Is.EqualTo(new Vector4(7f, 8f, 6f, 9f)));
			Assert.That(vec.YZYX(), Is.EqualTo(new Vector4(7f, 8f, 7f, 6f)));
			Assert.That(vec.YZYY(), Is.EqualTo(new Vector4(7f, 8f, 7f, 7f)));
			Assert.That(vec.YZYZ(), Is.EqualTo(new Vector4(7f, 8f, 7f, 8f)));
			Assert.That(vec.YZYW(), Is.EqualTo(new Vector4(7f, 8f, 7f, 9f)));
			Assert.That(vec.YZZX(), Is.EqualTo(new Vector4(7f, 8f, 8f, 6f)));
			Assert.That(vec.YZZY(), Is.EqualTo(new Vector4(7f, 8f, 8f, 7f)));
			Assert.That(vec.YZZZ(), Is.EqualTo(new Vector4(7f, 8f, 8f, 8f)));
			Assert.That(vec.YZZW(), Is.EqualTo(new Vector4(7f, 8f, 8f, 9f)));
			Assert.That(vec.YZWX(), Is.EqualTo(new Vector4(7f, 8f, 9f, 6f)));
			Assert.That(vec.YZWY(), Is.EqualTo(new Vector4(7f, 8f, 9f, 7f)));
			Assert.That(vec.YZWZ(), Is.EqualTo(new Vector4(7f, 8f, 9f, 8f)));
			Assert.That(vec.YZWW(), Is.EqualTo(new Vector4(7f, 8f, 9f, 9f)));
			Assert.That(vec.YWXX(), Is.EqualTo(new Vector4(7f, 9f, 6f, 6f)));
			Assert.That(vec.YWXY(), Is.EqualTo(new Vector4(7f, 9f, 6f, 7f)));
			Assert.That(vec.YWXZ(), Is.EqualTo(new Vector4(7f, 9f, 6f, 8f)));
			Assert.That(vec.YWXW(), Is.EqualTo(new Vector4(7f, 9f, 6f, 9f)));
			Assert.That(vec.YWYX(), Is.EqualTo(new Vector4(7f, 9f, 7f, 6f)));
			Assert.That(vec.YWYY(), Is.EqualTo(new Vector4(7f, 9f, 7f, 7f)));
			Assert.That(vec.YWYZ(), Is.EqualTo(new Vector4(7f, 9f, 7f, 8f)));
			Assert.That(vec.YWYW(), Is.EqualTo(new Vector4(7f, 9f, 7f, 9f)));
			Assert.That(vec.YWZX(), Is.EqualTo(new Vector4(7f, 9f, 8f, 6f)));
			Assert.That(vec.YWZY(), Is.EqualTo(new Vector4(7f, 9f, 8f, 7f)));
			Assert.That(vec.YWZZ(), Is.EqualTo(new Vector4(7f, 9f, 8f, 8f)));
			Assert.That(vec.YWZW(), Is.EqualTo(new Vector4(7f, 9f, 8f, 9f)));
			Assert.That(vec.YWWX(), Is.EqualTo(new Vector4(7f, 9f, 9f, 6f)));
			Assert.That(vec.YWWY(), Is.EqualTo(new Vector4(7f, 9f, 9f, 7f)));
			Assert.That(vec.YWWZ(), Is.EqualTo(new Vector4(7f, 9f, 9f, 8f)));
			Assert.That(vec.YWWW(), Is.EqualTo(new Vector4(7f, 9f, 9f, 9f)));
			Assert.That(vec.ZXXX(), Is.EqualTo(new Vector4(8f, 6f, 6f, 6f)));
			Assert.That(vec.ZXXY(), Is.EqualTo(new Vector4(8f, 6f, 6f, 7f)));
			Assert.That(vec.ZXXZ(), Is.EqualTo(new Vector4(8f, 6f, 6f, 8f)));
			Assert.That(vec.ZXXW(), Is.EqualTo(new Vector4(8f, 6f, 6f, 9f)));
			Assert.That(vec.ZXYX(), Is.EqualTo(new Vector4(8f, 6f, 7f, 6f)));
			Assert.That(vec.ZXYY(), Is.EqualTo(new Vector4(8f, 6f, 7f, 7f)));
			Assert.That(vec.ZXYZ(), Is.EqualTo(new Vector4(8f, 6f, 7f, 8f)));
			Assert.That(vec.ZXYW(), Is.EqualTo(new Vector4(8f, 6f, 7f, 9f)));
			Assert.That(vec.ZXZX(), Is.EqualTo(new Vector4(8f, 6f, 8f, 6f)));
			Assert.That(vec.ZXZY(), Is.EqualTo(new Vector4(8f, 6f, 8f, 7f)));
			Assert.That(vec.ZXZZ(), Is.EqualTo(new Vector4(8f, 6f, 8f, 8f)));
			Assert.That(vec.ZXZW(), Is.EqualTo(new Vector4(8f, 6f, 8f, 9f)));
			Assert.That(vec.ZXWX(), Is.EqualTo(new Vector4(8f, 6f, 9f, 6f)));
			Assert.That(vec.ZXWY(), Is.EqualTo(new Vector4(8f, 6f, 9f, 7f)));
			Assert.That(vec.ZXWZ(), Is.EqualTo(new Vector4(8f, 6f, 9f, 8f)));
			Assert.That(vec.ZXWW(), Is.EqualTo(new Vector4(8f, 6f, 9f, 9f)));
			Assert.That(vec.ZYXX(), Is.EqualTo(new Vector4(8f, 7f, 6f, 6f)));
			Assert.That(vec.ZYXY(), Is.EqualTo(new Vector4(8f, 7f, 6f, 7f)));
			Assert.That(vec.ZYXZ(), Is.EqualTo(new Vector4(8f, 7f, 6f, 8f)));
			Assert.That(vec.ZYXW(), Is.EqualTo(new Vector4(8f, 7f, 6f, 9f)));
			Assert.That(vec.ZYYX(), Is.EqualTo(new Vector4(8f, 7f, 7f, 6f)));
			Assert.That(vec.ZYYY(), Is.EqualTo(new Vector4(8f, 7f, 7f, 7f)));
			Assert.That(vec.ZYYZ(), Is.EqualTo(new Vector4(8f, 7f, 7f, 8f)));
			Assert.That(vec.ZYYW(), Is.EqualTo(new Vector4(8f, 7f, 7f, 9f)));
			Assert.That(vec.ZYZX(), Is.EqualTo(new Vector4(8f, 7f, 8f, 6f)));
			Assert.That(vec.ZYZY(), Is.EqualTo(new Vector4(8f, 7f, 8f, 7f)));
			Assert.That(vec.ZYZZ(), Is.EqualTo(new Vector4(8f, 7f, 8f, 8f)));
			Assert.That(vec.ZYZW(), Is.EqualTo(new Vector4(8f, 7f, 8f, 9f)));
			Assert.That(vec.ZYWX(), Is.EqualTo(new Vector4(8f, 7f, 9f, 6f)));
			Assert.That(vec.ZYWY(), Is.EqualTo(new Vector4(8f, 7f, 9f, 7f)));
			Assert.That(vec.ZYWZ(), Is.EqualTo(new Vector4(8f, 7f, 9f, 8f)));
			Assert.That(vec.ZYWW(), Is.EqualTo(new Vector4(8f, 7f, 9f, 9f)));
			Assert.That(vec.ZZXX(), Is.EqualTo(new Vector4(8f, 8f, 6f, 6f)));
			Assert.That(vec.ZZXY(), Is.EqualTo(new Vector4(8f, 8f, 6f, 7f)));
			Assert.That(vec.ZZXZ(), Is.EqualTo(new Vector4(8f, 8f, 6f, 8f)));
			Assert.That(vec.ZZXW(), Is.EqualTo(new Vector4(8f, 8f, 6f, 9f)));
			Assert.That(vec.ZZYX(), Is.EqualTo(new Vector4(8f, 8f, 7f, 6f)));
			Assert.That(vec.ZZYY(), Is.EqualTo(new Vector4(8f, 8f, 7f, 7f)));
			Assert.That(vec.ZZYZ(), Is.EqualTo(new Vector4(8f, 8f, 7f, 8f)));
			Assert.That(vec.ZZYW(), Is.EqualTo(new Vector4(8f, 8f, 7f, 9f)));
			Assert.That(vec.ZZZX(), Is.EqualTo(new Vector4(8f, 8f, 8f, 6f)));
			Assert.That(vec.ZZZY(), Is.EqualTo(new Vector4(8f, 8f, 8f, 7f)));
			Assert.That(vec.ZZZZ(), Is.EqualTo(new Vector4(8f, 8f, 8f, 8f)));
			Assert.That(vec.ZZZW(), Is.EqualTo(new Vector4(8f, 8f, 8f, 9f)));
			Assert.That(vec.ZZWX(), Is.EqualTo(new Vector4(8f, 8f, 9f, 6f)));
			Assert.That(vec.ZZWY(), Is.EqualTo(new Vector4(8f, 8f, 9f, 7f)));
			Assert.That(vec.ZZWZ(), Is.EqualTo(new Vector4(8f, 8f, 9f, 8f)));
			Assert.That(vec.ZZWW(), Is.EqualTo(new Vector4(8f, 8f, 9f, 9f)));
			Assert.That(vec.ZWXX(), Is.EqualTo(new Vector4(8f, 9f, 6f, 6f)));
			Assert.That(vec.ZWXY(), Is.EqualTo(new Vector4(8f, 9f, 6f, 7f)));
			Assert.That(vec.ZWXZ(), Is.EqualTo(new Vector4(8f, 9f, 6f, 8f)));
			Assert.That(vec.ZWXW(), Is.EqualTo(new Vector4(8f, 9f, 6f, 9f)));
			Assert.That(vec.ZWYX(), Is.EqualTo(new Vector4(8f, 9f, 7f, 6f)));
			Assert.That(vec.ZWYY(), Is.EqualTo(new Vector4(8f, 9f, 7f, 7f)));
			Assert.That(vec.ZWYZ(), Is.EqualTo(new Vector4(8f, 9f, 7f, 8f)));
			Assert.That(vec.ZWYW(), Is.EqualTo(new Vector4(8f, 9f, 7f, 9f)));
			Assert.That(vec.ZWZX(), Is.EqualTo(new Vector4(8f, 9f, 8f, 6f)));
			Assert.That(vec.ZWZY(), Is.EqualTo(new Vector4(8f, 9f, 8f, 7f)));
			Assert.That(vec.ZWZZ(), Is.EqualTo(new Vector4(8f, 9f, 8f, 8f)));
			Assert.That(vec.ZWZW(), Is.EqualTo(new Vector4(8f, 9f, 8f, 9f)));
			Assert.That(vec.ZWWX(), Is.EqualTo(new Vector4(8f, 9f, 9f, 6f)));
			Assert.That(vec.ZWWY(), Is.EqualTo(new Vector4(8f, 9f, 9f, 7f)));
			Assert.That(vec.ZWWZ(), Is.EqualTo(new Vector4(8f, 9f, 9f, 8f)));
			Assert.That(vec.ZWWW(), Is.EqualTo(new Vector4(8f, 9f, 9f, 9f)));
			Assert.That(vec.WXXX(), Is.EqualTo(new Vector4(9f, 6f, 6f, 6f)));
			Assert.That(vec.WXXY(), Is.EqualTo(new Vector4(9f, 6f, 6f, 7f)));
			Assert.That(vec.WXXZ(), Is.EqualTo(new Vector4(9f, 6f, 6f, 8f)));
			Assert.That(vec.WXXW(), Is.EqualTo(new Vector4(9f, 6f, 6f, 9f)));
			Assert.That(vec.WXYX(), Is.EqualTo(new Vector4(9f, 6f, 7f, 6f)));
			Assert.That(vec.WXYY(), Is.EqualTo(new Vector4(9f, 6f, 7f, 7f)));
			Assert.That(vec.WXYZ(), Is.EqualTo(new Vector4(9f, 6f, 7f, 8f)));
			Assert.That(vec.WXYW(), Is.EqualTo(new Vector4(9f, 6f, 7f, 9f)));
			Assert.That(vec.WXZX(), Is.EqualTo(new Vector4(9f, 6f, 8f, 6f)));
			Assert.That(vec.WXZY(), Is.EqualTo(new Vector4(9f, 6f, 8f, 7f)));
			Assert.That(vec.WXZZ(), Is.EqualTo(new Vector4(9f, 6f, 8f, 8f)));
			Assert.That(vec.WXZW(), Is.EqualTo(new Vector4(9f, 6f, 8f, 9f)));
			Assert.That(vec.WXWX(), Is.EqualTo(new Vector4(9f, 6f, 9f, 6f)));
			Assert.That(vec.WXWY(), Is.EqualTo(new Vector4(9f, 6f, 9f, 7f)));
			Assert.That(vec.WXWZ(), Is.EqualTo(new Vector4(9f, 6f, 9f, 8f)));
			Assert.That(vec.WXWW(), Is.EqualTo(new Vector4(9f, 6f, 9f, 9f)));
			Assert.That(vec.WYXX(), Is.EqualTo(new Vector4(9f, 7f, 6f, 6f)));
			Assert.That(vec.WYXY(), Is.EqualTo(new Vector4(9f, 7f, 6f, 7f)));
			Assert.That(vec.WYXZ(), Is.EqualTo(new Vector4(9f, 7f, 6f, 8f)));
			Assert.That(vec.WYXW(), Is.EqualTo(new Vector4(9f, 7f, 6f, 9f)));
			Assert.That(vec.WYYX(), Is.EqualTo(new Vector4(9f, 7f, 7f, 6f)));
			Assert.That(vec.WYYY(), Is.EqualTo(new Vector4(9f, 7f, 7f, 7f)));
			Assert.That(vec.WYYZ(), Is.EqualTo(new Vector4(9f, 7f, 7f, 8f)));
			Assert.That(vec.WYYW(), Is.EqualTo(new Vector4(9f, 7f, 7f, 9f)));
			Assert.That(vec.WYZX(), Is.EqualTo(new Vector4(9f, 7f, 8f, 6f)));
			Assert.That(vec.WYZY(), Is.EqualTo(new Vector4(9f, 7f, 8f, 7f)));
			Assert.That(vec.WYZZ(), Is.EqualTo(new Vector4(9f, 7f, 8f, 8f)));
			Assert.That(vec.WYZW(), Is.EqualTo(new Vector4(9f, 7f, 8f, 9f)));
			Assert.That(vec.WYWX(), Is.EqualTo(new Vector4(9f, 7f, 9f, 6f)));
			Assert.That(vec.WYWY(), Is.EqualTo(new Vector4(9f, 7f, 9f, 7f)));
			Assert.That(vec.WYWZ(), Is.EqualTo(new Vector4(9f, 7f, 9f, 8f)));
			Assert.That(vec.WYWW(), Is.EqualTo(new Vector4(9f, 7f, 9f, 9f)));
			Assert.That(vec.WZXX(), Is.EqualTo(new Vector4(9f, 8f, 6f, 6f)));
			Assert.That(vec.WZXY(), Is.EqualTo(new Vector4(9f, 8f, 6f, 7f)));
			Assert.That(vec.WZXZ(), Is.EqualTo(new Vector4(9f, 8f, 6f, 8f)));
			Assert.That(vec.WZXW(), Is.EqualTo(new Vector4(9f, 8f, 6f, 9f)));
			Assert.That(vec.WZYX(), Is.EqualTo(new Vector4(9f, 8f, 7f, 6f)));
			Assert.That(vec.WZYY(), Is.EqualTo(new Vector4(9f, 8f, 7f, 7f)));
			Assert.That(vec.WZYZ(), Is.EqualTo(new Vector4(9f, 8f, 7f, 8f)));
			Assert.That(vec.WZYW(), Is.EqualTo(new Vector4(9f, 8f, 7f, 9f)));
			Assert.That(vec.WZZX(), Is.EqualTo(new Vector4(9f, 8f, 8f, 6f)));
			Assert.That(vec.WZZY(), Is.EqualTo(new Vector4(9f, 8f, 8f, 7f)));
			Assert.That(vec.WZZZ(), Is.EqualTo(new Vector4(9f, 8f, 8f, 8f)));
			Assert.That(vec.WZZW(), Is.EqualTo(new Vector4(9f, 8f, 8f, 9f)));
			Assert.That(vec.WZWX(), Is.EqualTo(new Vector4(9f, 8f, 9f, 6f)));
			Assert.That(vec.WZWY(), Is.EqualTo(new Vector4(9f, 8f, 9f, 7f)));
			Assert.That(vec.WZWZ(), Is.EqualTo(new Vector4(9f, 8f, 9f, 8f)));
			Assert.That(vec.WZWW(), Is.EqualTo(new Vector4(9f, 8f, 9f, 9f)));
			Assert.That(vec.WWXX(), Is.EqualTo(new Vector4(9f, 9f, 6f, 6f)));
			Assert.That(vec.WWXY(), Is.EqualTo(new Vector4(9f, 9f, 6f, 7f)));
			Assert.That(vec.WWXZ(), Is.EqualTo(new Vector4(9f, 9f, 6f, 8f)));
			Assert.That(vec.WWXW(), Is.EqualTo(new Vector4(9f, 9f, 6f, 9f)));
			Assert.That(vec.WWYX(), Is.EqualTo(new Vector4(9f, 9f, 7f, 6f)));
			Assert.That(vec.WWYY(), Is.EqualTo(new Vector4(9f, 9f, 7f, 7f)));
			Assert.That(vec.WWYZ(), Is.EqualTo(new Vector4(9f, 9f, 7f, 8f)));
			Assert.That(vec.WWYW(), Is.EqualTo(new Vector4(9f, 9f, 7f, 9f)));
			Assert.That(vec.WWZX(), Is.EqualTo(new Vector4(9f, 9f, 8f, 6f)));
			Assert.That(vec.WWZY(), Is.EqualTo(new Vector4(9f, 9f, 8f, 7f)));
			Assert.That(vec.WWZZ(), Is.EqualTo(new Vector4(9f, 9f, 8f, 8f)));
			Assert.That(vec.WWZW(), Is.EqualTo(new Vector4(9f, 9f, 8f, 9f)));
			Assert.That(vec.WWWX(), Is.EqualTo(new Vector4(9f, 9f, 9f, 6f)));
			Assert.That(vec.WWWY(), Is.EqualTo(new Vector4(9f, 9f, 9f, 7f)));
			Assert.That(vec.WWWZ(), Is.EqualTo(new Vector4(9f, 9f, 9f, 8f)));
			Assert.That(vec.WWWW(), Is.EqualTo(new Vector4(9f, 9f, 9f, 9f)));
		});
	}
}